# Generated by Django 3.1.6 on 2021-02-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('available', models.BooleanField(default=False)),
                ('resources', models.ManyToManyField(to='resources.Resource')),
            ],
        ),
    ]
