# Generated by Django 3.1.6 on 2021-02-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('core', '0002_turpoint_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='turpoint',
            name='comments',
            field=models.ManyToManyField(to='comments.Comment'),
        ),
    ]
