# Generated by Django 3.1.6 on 2021-02-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_turpoint_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='turpoint',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='turpoints'),
        ),
    ]
